language: cpp

compiler: gcc

cache: apt

env:
    - WITH_SUITE=true WITH_APP=false WITH_CUDA=false
    - WITH_SUITE=false WITH_APP=true WITH_CUDA=false

before_install:
    - export NUM_THREADS=4
    - sudo apt-get install -y python-software-properties;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install -y gcc-4.8 g++-4.8;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50;
      git clone https://github.com/Itseez/opencv.git;
      cd opencv;
      git checkout 2.4.9;
      mkdir build;
      cd build;
      cmake ..;
      make -j$NUM_THREADS;
      sudo make -j$NUM_THREADS install;
      cd ../..;

install:
    - if $WITH_SUITE; then
      travis_wait sudo -E ./travis-scripts/suite_deps.sh;
      fi
    - if $WITH_APP; then
      cd sirius-application;
      travis_wait sudo -E ./get-dependencies.sh;
      ./get-kaldi.sh;
      cd ..;
      fi

before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:/usr/lib
    - export PATH=/home/travis/miniconda/bin:$PATH

script:
    - if $WITH_SUITE; then
      cd sirius-suite;
      ./prepare.sh && make && cd ..;
      fi
    - if $WITH_APP; then
      cd sirius-application && ./compile-sirius-servers.sh && cd ..;
      fi
